# Generated by Django 5.0.6 on 2024-07-21 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.student')),
                ('english', models.IntegerField(default=0)),
                ('maths', models.IntegerField(default=0)),
                ('physics', models.IntegerField(default=0)),
                ('chemistry', models.IntegerField(default=0)),
                ('computer', models.IntegerField(default=0)),
            ],
        ),
    ]
